name: Dan Maxwell
favicon: null
layout_spectrum: 0
typography_spectrum: 0.04688
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090909'
    - '#f9fae8'
    - '#e39545'
    - '#5d5a49'
    - '#84250f'
  brandStrength: 0.3146293165627867
  lightness: 0.3125
  saturation: 0.5625
  rhythmicContrast: 0
purpose: []
