name: Raymond Street
favicon: null
layout_spectrum: 1
typography_spectrum: 0.07549
title: 'The doings of Scarlett, Dash, Bryony and Dan'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebf4f1'
    - '#0b0c11'
    - '#4a5551'
    - '#9d0520'
    - '#f37703'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
