name: Dan Maxwell
favicon: null
layout_spectrum: 0.6144000694621354
typography_spectrum: 0.93484155414626
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3146293165627867
  lightness: 0.32967260386794806
  saturation: 0.07706533884629607
  rhythmicContrast: 0.15238630585372448
purpose: []
